#!/usr/bin/env bash

PROBLEM_SIZE=$1
ITERATIVE_METHOD=$2
NUM_PROCS=$3

# Set openfoam environment
source /root/.bashrc

# Prepare benchmark
ln -sf /opt/hpc/Lid_driven_cavity-3d/${PROBLEM_SIZE} /opt/benchmark
ln -sf /opt/benchmark/system/fvSolution.${ITERATIVE_METHOD} /opt/benchmark/system/fvSolution
mv /opt/benchmark/constant/transportProperties /opt/benchmark/constant/physicalProperties
sed -i "s/^numberOfSubdomains.*/numberOfSubdomains ${NUM_PROCS};/g" /opt/benchmark/system/decomposeParDict

# Stage benchmark datafiles
cd /opt/benchmark
blockMesh
decomposePar -force

for host in $( echo "$VC_MPI_WORKER_HOSTS" | tr ',' ' '); do
  while ! rsync -avL /opt/benchmark ${host}:/opt/ ; do
    echo "Failed to connect to $host, waiting before retry..."
    sleep 5
  done  
done

# When using the --host option, the number of slots on the host defaults to 1
# When using --hostfile, the number of slots on the host default to the number of CPUs
# We want the hostfile behaviour, but including localhost
HOSTFILE="$(mktemp)"
echo "localhost" > $HOSTFILE
cat /etc/volcano/mpi_worker.host >> $HOSTFILE

exec /usr/bin/time -p \
  mpirun \
    --allow-run-as-root \
    --display-map \
    --hostfile $HOSTFILE \
    -np "${NUM_PROCS}" \
    --map-by node \
    --mca btl "${MPIRUN_MCA_BTL:-"self,tcp"}" \
    icoFoam -parallel
