#!/usr/bin/env bash

PROBLEM_SIZE=$1
ITERATIVE_METHOD=$2
NUM_PROCS=$3

# Set openfoam environment
source /root/.bashrc

# Prepare benchmark
ln -sf /opt/hpc/Lid_driven_cavity-3d/${PROBLEM_SIZE} /opt/benchmark
ln -sf /opt/benchmark/system/fvSolution.${ITERATIVE_METHOD} /opt/benchmark/system/fvSolution
mv /opt/benchmark/constant/transportProperties /opt/benchmark/constant/physicalProperties
sed -i "s/^numberOfSubdomains.*/numberOfSubdomains ${NUM_PROCS};/g" /opt/benchmark/system/decomposeParDict

# Stage benchmark datafiles
cd /opt/benchmark
blockMesh
decomposePar -force

for host in $( echo "$VC_MPI_WORKER_HOSTS" | tr ',' ' '); do
  while ! rsync -avL /opt/benchmark ${host}:/opt/ ; do
    echo "Failed to connect to $host, waiting before retry..."
    sleep 5
  done  
done

exec /usr/bin/time -p \
  mpirun \
    --allow-run-as-root \
    --display-map \
    --host "localhost,${VC_MPI_WORKER_HOSTS}" \
    -np "${NUM_PROCS}" \
    --bynode \
    --mca btl "${MPIRUN_MCA_BTL:-"self,tcp"}" \
    icoFoam -parallel
